version: "3.7"

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      NODE_PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_DIALECT: postgres
    env_file:
      - ./src/config/index.js
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
    db:
      driver: local
